/**
 * `platform sync`: turns every app's manifest into the platform wiring under
 * `generated/platform/`. `--check` fails when the committed output differs
 * from what the manifests generate, so CI catches drift.
 *
 * Manifests are read as `apps/<folder>/platform.app.json` only (compile a
 * `platform.app.ts` first with `platform manifest compile`): sync never
 * executes app code, so it can run against another checkout (`--root`).
 *
 * Generators so far (ADR 0001 §3, #769):
 *   generated/platform/launcher-registry.json   the launcher tiles (ui.launcher)
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { formatProblems, validateManifest, type AppManifest } from "@asafarim/app-manifest";

/** Files that document the directory rather than being generator output. */
const NOT_GENERATED = new Set(["README.md", ".gitkeep"]);

export const MANIFEST_FILE = "platform.app.json";
export const LAUNCHER_REGISTRY = "generated/platform/launcher-registry.json";

export interface SyncResult {
  ok: boolean;
  lines: string[];
}

/** The workspace root: the nearest ancestor holding pnpm-workspace.yaml. */
export function findRepoRoot(from: string): string {
  let dir = path.resolve(from);
  for (;;) {
    if (existsSync(path.join(dir, "pnpm-workspace.yaml"))) return dir;
    const parent = path.dirname(dir);
    if (parent === dir) throw new Error(`No pnpm-workspace.yaml found above ${from}`);
    dir = parent;
  }
}

/** `apps/<id>/platform.app.json` files, sorted by app folder. */
export function discoverManifests(root: string): string[] {
  const appsDir = path.join(root, "apps");
  if (!existsSync(appsDir)) return [];
  return readdirSync(appsDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => path.join(appsDir, entry.name, MANIFEST_FILE))
    .filter((file) => existsSync(file))
    .sort();
}

/** Files under generated/platform/ that a generator would own. */
export function generatedFiles(root: string): string[] {
  const dir = path.join(root, "generated", "platform");
  if (!existsSync(dir)) return [];
  return readdirSync(dir, { recursive: true, withFileTypes: true })
    .filter((entry) => entry.isFile() && !NOT_GENERATED.has(entry.name))
    .map((entry) => path.relative(root, path.join(entry.parentPath, entry.name)).split(path.sep).join("/"))
    .sort();
}

/** One launcher tile, as the platform's registry consumes it. */
export interface LauncherEntry {
  key: string;
  name: string;
  description: string;
  glyph: string;
  meta: string;
  status: "active" | "coming-soon";
  access: "public" | "authenticated";
  requiresAccountToUse?: boolean;
  order: number;
}

/** The launcher registry: every manifest with a `ui.launcher`, by `order` then id. */
export function launcherRegistry(manifests: AppManifest[]): LauncherEntry[] {
  return manifests
    .filter((m) => m.ui.launcher !== undefined)
    .map((m) => {
      const l = m.ui.launcher!;
      return {
        key: m.id,
        name: m.name,
        description: l.description,
        glyph: m.ui.glyph,
        meta: l.meta,
        status: m.ui.status,
        access: l.access,
        ...(l.requiresAccountToUse === undefined ? {} : { requiresAccountToUse: l.requiresAccountToUse }),
        order: l.order,
      };
    })
    .sort((a, b) => a.order - b.order || a.key.localeCompare(b.key));
}

export function renderLauncherRegistry(entries: LauncherEntry[]): string {
  const doc = {
    $comment:
      "Generated by `platform sync` from apps/*/platform.app.json (ui.launcher). Do not edit: change the manifest and run sync.",
    apps: entries,
  };
  return `${JSON.stringify(doc, null, 2)}\n`;
}

interface Loaded {
  manifests: AppManifest[];
  problems: string[];
}

function loadManifests(root: string): Loaded {
  const manifests: AppManifest[] = [];
  const problems: string[] = [];
  for (const file of discoverManifests(root)) {
    const shown = path.relative(root, file).split(path.sep).join("/");
    let value: unknown;
    try {
      value = JSON.parse(readFileSync(file, "utf8"));
    } catch (error) {
      problems.push(`✖ ${shown}: can't read it (${(error as Error).message})`);
      continue;
    }
    const result = validateManifest(value);
    if (result.ok) manifests.push(result.manifest);
    else problems.push(`✖ ${shown}: ${result.problems.length} problem(s)`, formatProblems(result.problems));
  }
  const seen = new Map<string, number>();
  for (const m of manifests) seen.set(m.id, (seen.get(m.id) ?? 0) + 1);
  for (const [id, n] of seen) if (n > 1) problems.push(`✖ ${n} manifests declare the id "${id}"`);
  return { manifests, problems };
}

/** What the generators produce for these manifests: path → content. */
export function generate(manifests: AppManifest[]): Map<string, string> {
  const out = new Map<string, string>();
  const launcher = launcherRegistry(manifests);
  if (launcher.length > 0) out.set(LAUNCHER_REGISTRY, renderLauncherRegistry(launcher));
  return out;
}

const normalise = (s: string) => s.replace(/\r\n/g, "\n");

export function sync(root: string, opts: { check: boolean }): SyncResult {
  const { manifests, problems } = loadManifests(root);
  const lines = [`Found ${manifests.length} valid app manifest(s).`];
  if (problems.length > 0) {
    lines.push("Fix these manifests first:", ...problems);
    return { ok: false, lines };
  }

  const expected = generate(manifests);
  const onDisk = new Set(generatedFiles(root));
  const stale: string[] = [];
  for (const [rel, content] of expected) {
    const file = path.join(root, rel);
    const current = existsSync(file) ? normalise(readFileSync(file, "utf8")) : undefined;
    if (current !== content) stale.push(rel);
  }
  const stray = [...onDisk].filter((rel) => !expected.has(rel));

  if (opts.check) {
    if (stale.length === 0 && stray.length === 0) {
      lines.push(`generated/platform/ is up to date (${expected.size} file(s)).`);
      return { ok: true, lines };
    }
    if (stale.length > 0)
      lines.push(
        "Drift: these generated files are missing or out of date (run `platform sync`):",
        ...stale.map((s) => `  - ${s}`),
      );
    if (stray.length > 0)
      lines.push("Drift: generated/platform/ holds files that no manifest produces:", ...stray.map((s) => `  - ${s}`));
    return { ok: false, lines };
  }

  for (const rel of stale) {
    const file = path.join(root, rel);
    mkdirSync(path.dirname(file), { recursive: true });
    writeFileSync(file, expected.get(rel)!);
    lines.push(`  wrote ${rel}`);
  }
  if (stray.length > 0) {
    lines.push(
      "generated/platform/ holds files that no manifest produces; remove them:",
      ...stray.map((s) => `  - ${s}`),
    );
    return { ok: false, lines };
  }
  lines.push(
    stale.length === 0 ? "Nothing to generate: everything is up to date." : `Generated ${stale.length} file(s).`,
  );
  return { ok: true, lines };
}
