/**
 * `platform sync`: turns every app's manifest into the platform wiring under
 * `generated/platform/`. `--check` fails when the committed output differs
 * from what the manifests generate, so CI catches drift.
 *
 * Manifests are read as `apps/<folder>/platform.app.json` only (compile a
 * `platform.app.ts` first with `platform manifest compile`): sync never
 * executes app code, so it can run against another checkout (`--root`).
 *
 * Generators so far (ADR 0001 §3, §7, #769, P3.3a):
 *   generated/platform/launcher-registry.json     the launcher tiles (ui.launcher)
 *   generated/platform/gateway/dev.Caddyfile      the DEV gateway: one host per app, expose:false → 404,
 *                                                 forward_auth to core-api's /authz/check
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { formatProblems, validateManifest, type AppManifest } from "@asafarim/app-manifest";

/** Files that document the directory rather than being generator output. */
const NOT_GENERATED = new Set(["README.md", ".gitkeep"]);

export const MANIFEST_FILE = "platform.app.json";
export const LAUNCHER_REGISTRY = "generated/platform/launcher-registry.json";
export const GATEWAY_CADDYFILE = "generated/platform/gateway/dev.Caddyfile";
/** Where the dev gateway listens, and the host suffix each app is served under (<id>.localhost:8080). */
export const GATEWAY_DEV_PORT = 8080;
/** Answered 200 on the catch-all site; compose.dev.yml's healthcheck calls it (BusyBox wget only exits 0 on a 2xx). */
export const GATEWAY_HEALTH_PATH = "/gateway-health";

export interface SyncResult {
  ok: boolean;
  lines: string[];
}

/** The workspace root: the nearest ancestor holding pnpm-workspace.yaml. */
export function findRepoRoot(from: string): string {
  let dir = path.resolve(from);
  for (;;) {
    if (existsSync(path.join(dir, "pnpm-workspace.yaml"))) return dir;
    const parent = path.dirname(dir);
    if (parent === dir) throw new Error(`No pnpm-workspace.yaml found above ${from}`);
    dir = parent;
  }
}

/** `apps/<id>/platform.app.json` files, sorted by app folder. */
export function discoverManifests(root: string): string[] {
  const appsDir = path.join(root, "apps");
  if (!existsSync(appsDir)) return [];
  return readdirSync(appsDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => path.join(appsDir, entry.name, MANIFEST_FILE))
    .filter((file) => existsSync(file))
    .sort();
}

/** Files under generated/platform/ that a generator would own. */
export function generatedFiles(root: string): string[] {
  const dir = path.join(root, "generated", "platform");
  if (!existsSync(dir)) return [];
  return readdirSync(dir, { recursive: true, withFileTypes: true })
    .filter((entry) => entry.isFile() && !NOT_GENERATED.has(entry.name))
    .map((entry) => path.relative(root, path.join(entry.parentPath, entry.name)).split(path.sep).join("/"))
    .sort();
}

/** One launcher tile, as the platform's registry consumes it. */
export interface LauncherEntry {
  key: string;
  name: string;
  description: string;
  glyph: string;
  meta: string;
  status: "active" | "coming-soon";
  access: "public" | "authenticated";
  requiresAccountToUse?: boolean;
  order: number;
}

/** The launcher registry: every manifest with a `ui.launcher`, by `order` then id. */
export function launcherRegistry(manifests: AppManifest[]): LauncherEntry[] {
  return (
    manifests
      .filter((m) => m.ui.launcher !== undefined)
      .map((m) => {
        const l = m.ui.launcher!;
        return {
          key: m.id,
          name: m.name,
          description: l.description,
          glyph: m.ui.glyph,
          meta: l.meta,
          status: m.ui.status,
          access: l.access,
          ...(l.requiresAccountToUse === undefined ? {} : { requiresAccountToUse: l.requiresAccountToUse }),
          order: l.order,
        };
      })
      // Code-unit tie-break, not localeCompare: --check compares bytes, so the
      // order must not depend on the host's collation.
      .sort((a, b) => a.order - b.order || (a.key < b.key ? -1 : a.key > b.key ? 1 : 0))
  );
}

export function renderLauncherRegistry(entries: LauncherEntry[]): string {
  const doc = {
    $comment:
      "Generated by `platform sync` from apps/*/platform.app.json (ui.launcher). Do not edit: change the manifest and run sync.",
    apps: entries,
  };
  return `${JSON.stringify(doc, null, 2)}\n`;
}

/**
 * The env var holding an app's upstream (host:port) in the generated gateway:
 * OS_APP_<ID>_UPSTREAM, e.g. OS_APP_NOTES_UPSTREAM. The dev scripts fill it in.
 */
export const gatewayUpstreamVar = (appId: string) => `OS_APP_${appId.toUpperCase().replace(/-/g, "_")}_UPSTREAM`;
export const GATEWAY_CORE_API_VAR = "OS_CORE_API_UPSTREAM";
export const GATEWAY_IDENTITY_VAR = "OS_IDENTITY_UPSTREAM";

/**
 * A route glob (`*` one segment, `**` any depth) as Caddy `path` patterns. Caddy's `*` also crosses
 * slashes, so a hidden pattern can only over-block, never under-block; the core-api hook (which
 * normalises the path) is the exact check, this is the gateway's own first line.
 */
export function caddyPathPatterns(glob: string): string[] {
  if (glob.endsWith("/**")) {
    const base = glob.slice(0, -3) || "/";
    return [base, `${base === "/" ? "" : base}/*`].map((p) => p.replace(/\*\*/g, "*"));
  }
  return [glob.replace(/\*\*/g, "*")];
}

/**
 * The DEV gateway (P3.3a): local and CI only, plain HTTP on 127.0.0.1:8080.
 * Every request to an app's host is checked by core-api (forward_auth →
 * /authz/check), which decides from the app's live lifecycle state and the
 * manifest's routes; Caddy proxies only what it allows. Which app a request
 * belongs to is stamped here (X-Asafarim-App), per site block.
 */
export function renderGatewayCaddyfile(manifests: AppManifest[]): string {
  const apps = [...manifests].sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
  const port = GATEWAY_DEV_PORT;
  const out: string[] = [
    "# Generated by `platform sync` from apps/*/platform.app.json (routes). Do not edit: change the manifest and run sync.",
    "# The DEV gateway (P3.3a): local and CI only. Production sites are generated separately (ADR 0001 §7).",
    "#",
    "# Per app, <id>.localhost: expose:false paths answer 404 here; every other request is checked by core-api",
    "# (forward_auth → /authz/check: 503 not active, 404 hidden, 401, 403 naming the permission, or 200) and",
    "# only then proxied to the app. Upstreams come from the environment (the dev scripts write .dev/gateway.env).",
    "{",
    "\tadmin off",
    "\tauto_https off",
    "}",
    "",
    `http://id.localhost:${port} {`,
    `\treverse_proxy {$${GATEWAY_IDENTITY_VAR}}`,
    "}",
    "",
    `http://api.localhost:${port} {`,
    `\treverse_proxy {$${GATEWAY_CORE_API_VAR}}`,
    "}",
  ];
  for (const m of apps) {
    out.push("", `http://${m.id}.localhost:${port} {`);
    const hidden = (m.routes ?? []).filter((r) => r.expose === false);
    hidden.forEach((r, i) => {
      out.push(`\t@hidden${i + 1} {`, `\t\tpath ${caddyPathPatterns(r.path).join(" ")}`);
      if (r.methods) out.push(`\t\tmethod ${r.methods.join(" ")}`);
      out.push("\t}", `\thandle @hidden${i + 1} {`, '\t\trespond "Not found" 404', "\t}");
    });
    out.push(
      "\thandle {",
      `\t\tforward_auth {$${GATEWAY_CORE_API_VAR}} {`,
      "\t\t\turi /authz/check",
      `\t\t\theader_up X-Asafarim-App ${m.id}`,
      "\t\t}",
      `\t\treverse_proxy {$${gatewayUpstreamVar(m.id)}}`,
      "\t}",
      "}",
    );
  }
  out.push(
    "",
    "# Any other host: a 404, and a health answer for the container's own check.",
    `http://:${port} {`,
    `\thandle ${GATEWAY_HEALTH_PATH} {`,
    '\t\trespond "ok" 200',
    "\t}",
    "\thandle {",
    '\t\trespond "Not found" 404',
    "\t}",
    "}",
    "",
  );
  return out.join("\n");
}

interface Loaded {
  manifests: AppManifest[];
  problems: string[];
}

function loadManifests(root: string): Loaded {
  const manifests: AppManifest[] = [];
  const problems: string[] = [];
  for (const file of discoverManifests(root)) {
    const shown = path.relative(root, file).split(path.sep).join("/");
    let value: unknown;
    try {
      value = JSON.parse(readFileSync(file, "utf8"));
    } catch (error) {
      problems.push(`✖ ${shown}: can't read it (${(error as Error).message})`);
      continue;
    }
    const result = validateManifest(value);
    if (result.ok) manifests.push(result.manifest);
    else problems.push(`✖ ${shown}: ${result.problems.length} problem(s)`, formatProblems(result.problems));
  }
  const seen = new Map<string, number>();
  for (const m of manifests) seen.set(m.id, (seen.get(m.id) ?? 0) + 1);
  for (const [id, n] of seen) if (n > 1) problems.push(`✖ ${n} manifests declare the id "${id}"`);
  return { manifests, problems };
}

/** What the generators produce for these manifests: path → content. */
export function generate(manifests: AppManifest[]): Map<string, string> {
  const out = new Map<string, string>();
  const launcher = launcherRegistry(manifests);
  if (launcher.length > 0) out.set(LAUNCHER_REGISTRY, renderLauncherRegistry(launcher));
  out.set(GATEWAY_CADDYFILE, renderGatewayCaddyfile(manifests));
  return out;
}

const normalise = (s: string) => s.replace(/\r\n/g, "\n");

export function sync(root: string, opts: { check: boolean }): SyncResult {
  const { manifests, problems } = loadManifests(root);
  const lines = [`Found ${manifests.length} valid app manifest(s).`];
  if (problems.length > 0) {
    lines.push("Fix these manifests first:", ...problems);
    return { ok: false, lines };
  }

  const expected = generate(manifests);
  const onDisk = new Set(generatedFiles(root));
  const stale: string[] = [];
  for (const [rel, content] of expected) {
    const file = path.join(root, rel);
    const current = existsSync(file) ? normalise(readFileSync(file, "utf8")) : undefined;
    if (current !== content) stale.push(rel);
  }
  const stray = [...onDisk].filter((rel) => !expected.has(rel));

  if (opts.check) {
    if (stale.length === 0 && stray.length === 0) {
      lines.push(`generated/platform/ is up to date (${expected.size} file(s)).`);
      return { ok: true, lines };
    }
    if (stale.length > 0)
      lines.push(
        "Drift: these generated files are missing or out of date (run `platform sync`):",
        ...stale.map((s) => `  - ${s}`),
      );
    if (stray.length > 0)
      lines.push("Drift: generated/platform/ holds files that no manifest produces:", ...stray.map((s) => `  - ${s}`));
    return { ok: false, lines };
  }

  for (const rel of stale) {
    const file = path.join(root, rel);
    mkdirSync(path.dirname(file), { recursive: true });
    writeFileSync(file, expected.get(rel)!);
    lines.push(`  wrote ${rel}`);
  }
  if (stray.length > 0) {
    lines.push(
      "generated/platform/ holds files that no manifest produces; remove them:",
      ...stray.map((s) => `  - ${s}`),
    );
    return { ok: false, lines };
  }
  lines.push(
    stale.length === 0 ? "Nothing to generate: everything is up to date." : `Generated ${stale.length} file(s).`,
  );
  return { ok: true, lines };
}
