/**
 * The progress file (src/progress.json) is the ONLY place the page's content changes: a new
 * milestone, a screenshot or a roadmap item is a one-file edit. This module types it and refuses a
 * file that would render a broken or unsafe page (a bad date, a link to an unexpected host, a
 * screenshot path that leaves the screenshots folder).
 */

export interface Milestone {
  /** The phase or step id, as the ADR and the issues name it: "P0", "P4.1", "Remove". */
  id: string;
  title: string;
  /** The day it was done, YYYY-MM-DD. */
  date: string;
  summary: string;
  /** The merged pull requests in the repository, by number. */
  prs: number[];
}

export interface Screenshot {
  /** A file name in public/screenshots/ (generated by `pnpm screenshots`). */
  file: string;
  title: string;
  alt: string;
  caption: string;
}

export interface RoadmapItem {
  id: string;
  title: string;
  summary: string;
}

export interface Link {
  label: string;
  href: string;
}

export interface Progress {
  updated: string;
  repo: string;
  shipped: Milestone[];
  screenshots: Screenshot[];
  roadmap: RoadmapItem[];
  links: Link[];
}

/** The only hosts the page links to. The smoke test checks the rendered page against the same list. */
export const ALLOWED_LINK_HOSTS: readonly string[] = ["github.com", "asafarim.com"];

const DATE = /^\d{4}-\d{2}-\d{2}$/;
const SCREENSHOT_FILE = /^[a-z0-9][a-z0-9-]*\.png$/;

class ProgressError extends Error {
  constructor(where: string, problem: string) {
    super(`progress.json: ${where} ${problem}`);
    this.name = "ProgressError";
  }
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function text(obj: Record<string, unknown>, key: string, where: string): string {
  const value = obj[key];
  if (typeof value !== "string" || value.trim() === "") throw new ProgressError(`${where}.${key}`, "must be text");
  return value;
}

function date(obj: Record<string, unknown>, key: string, where: string): string {
  const value = text(obj, key, where);
  const parsed = new Date(`${value}T00:00:00Z`);
  if (!DATE.test(value) || Number.isNaN(parsed.getTime()) || parsed.toISOString().slice(0, 10) !== value) {
    throw new ProgressError(`${where}.${key}`, `must be a YYYY-MM-DD date, got "${value}"`);
  }
  return value;
}

function list(obj: Record<string, unknown>, key: string, where: string): Record<string, unknown>[] {
  const value = obj[key];
  if (!Array.isArray(value) || value.length === 0)
    throw new ProgressError(`${where}.${key}`, "must be a non-empty list");
  return value.map((item, i) => {
    if (!isRecord(item)) throw new ProgressError(`${where}.${key}[${i}]`, "must be an object");
    return item;
  });
}

/** An https URL on one of ALLOWED_LINK_HOSTS (no credentials, no other port). */
export function isAllowedLink(href: string): boolean {
  let url: URL;
  try {
    url = new URL(href);
  } catch {
    return false;
  }
  return (
    url.protocol === "https:" &&
    url.username === "" &&
    url.password === "" &&
    url.port === "" &&
    ALLOWED_LINK_HOSTS.includes(url.hostname)
  );
}

function link(obj: Record<string, unknown>, key: string, where: string): string {
  const value = text(obj, key, where);
  if (!isAllowedLink(value)) {
    throw new ProgressError(`${where}.${key}`, `must be an https link to ${ALLOWED_LINK_HOSTS.join(" or ")}`);
  }
  return value;
}

function uniqueIds(items: { id: string }[], where: string): void {
  const seen = new Set<string>();
  for (const { id } of items) {
    if (seen.has(id)) throw new ProgressError(where, `has the id "${id}" twice`);
    seen.add(id);
  }
}

/** Validate and type the parsed progress file. Throws a ProgressError naming the first problem. */
export function parseProgress(raw: unknown): Progress {
  if (!isRecord(raw)) throw new ProgressError("the file", "must be a JSON object");
  const repo = link(raw, "repo", "");
  if (!/^https:\/\/github\.com\/[\w.-]+\/[\w.-]+$/.test(repo)) {
    throw new ProgressError(".repo", "must be a https://github.com/<owner>/<name> URL");
  }

  const shipped = list(raw, "shipped", "").map((m, i): Milestone => {
    const where = `shipped[${i}]`;
    const prs = m.prs;
    if (!Array.isArray(prs) || prs.length === 0 || !prs.every((n) => Number.isInteger(n) && (n as number) > 0)) {
      throw new ProgressError(`${where}.prs`, "must be a non-empty list of pull request numbers");
    }
    return {
      id: text(m, "id", where),
      title: text(m, "title", where),
      date: date(m, "date", where),
      summary: text(m, "summary", where),
      prs: prs as number[],
    };
  });
  uniqueIds(shipped, "shipped");

  const screenshots = list(raw, "screenshots", "").map((s, i): Screenshot => {
    const where = `screenshots[${i}]`;
    const file = text(s, "file", where);
    if (!SCREENSHOT_FILE.test(file)) {
      throw new ProgressError(`${where}.file`, `must be a plain .png file name in public/screenshots/, got "${file}"`);
    }
    return { file, title: text(s, "title", where), alt: text(s, "alt", where), caption: text(s, "caption", where) };
  });

  const roadmap = list(raw, "roadmap", "").map((r, i): RoadmapItem => ({
    id: text(r, "id", `roadmap[${i}]`),
    title: text(r, "title", `roadmap[${i}]`),
    summary: text(r, "summary", `roadmap[${i}]`),
  }));
  uniqueIds(roadmap, "roadmap");

  const links = list(raw, "links", "").map((l, i): Link => ({
    label: text(l, "label", `links[${i}]`),
    href: link(l, "href", `links[${i}]`),
  }));

  return { updated: date(raw, "updated", ""), repo, shipped, screenshots, roadmap, links };
}

/** The link to a merged pull request in the repository. */
export const pullRequestUrl = (repo: string, pr: number): string => `${repo}/pull/${pr}`;
